# Generated by Django 6.0.4 on 2026-04-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_created_at_alter_order_brownie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='brownie_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='cake_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
